/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#2170e4",
        "inverse-surface": "#2d3133",
        "tertiary": "#505f76",
        "surface-container": "#eceef0",
        "primary-fixed": "#6bff8f",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#001a42",
        "surface-container-high": "#e6e8ea",
        "on-secondary": "#ffffff",
        "primary-container": "#22c55e",
        "on-surface-variant": "#3d4a3d",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-container": "#fefcff",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "secondary-fixed": "#d8e2ff",
        "tertiary-container": "#9dadc6",
        "tertiary-fixed": "#d3e4fe",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#314156",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#005321",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#adc6ff",
        "outline": "#6d7b6c",
        "on-primary-container": "#004b1e",
        "primary-fixed-dim": "#4ae176",
        "outline-variant": "#bccbb9",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface-tint": "#006e2f",
        "inverse-primary": "#4ae176",
        "on-tertiary-fixed": "#0b1c30",
        "on-primary-fixed": "#002109",
        "secondary": "#0058be",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-dim": "#d8dadc",
        "primary": "#006e2f",
        "background": "#f7f9fb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.0rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "card-padding": "24px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "margin-page": "32px",
        "stack-md": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "stats-lg": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "stats-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
